ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'STREAM_DELAYED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'STREAM_ENDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'NEW_SCHEDULE_POSTED';
